version: "3"

services:
  app:
    image: petalinux:2019.2
    ipc: host
    network_mode: "host"
    build:
      context: .
      args:
        HOST_UID: "${USER_ID}"
        PETA_RUN_FILE: "${PETA_RUN_FILE}"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tftpboot:/tftpboot
